### ISSUE TITLE
 app does not sanitize invalid identifiers 

### ISSUE THREAD

**Issue by 3052** [xuthus5/json-to-pb#2]
valid input:

~~~json
{"1": "hello", "2": "world"}
~~~

invalid output:

~~~proto
syntax = "proto3";

package your.project.v1;

option go_package = "your/project;projectv1";


message AutoGenerated {
    string 2 = 0;
    string 1 = 1;
}
~~~

the field names and field numbers are both invalid:

https://protobuf.dev/reference/protobuf/proto3-spec/#identifiers
https://godocs.io/google.golang.org/protobuf/encoding/protowire#MinValidNumber

**Comment by xuthus5** [comment]
thx you for submitting the issue. I have now simply fixed this issue.
```json
{"a":"1", "b": {"2":"2"}}
```
got
```text
invalid field name 'B.2'
```
