### ISSUE TITLE
parser broken

### ISSUE THREAD

**Issue by 3052** [xuthus5/json-to-pb#3]
valid input

{"a1": "hello", "a2": "world"}

result:

invalid field name 'a1'

a1 is valid for both JSON and ProtoBuf

https://protobuf.dev/reference/protobuf/proto3-spec/#identifiers

**Comment by xuthus5** [comment]
I feel ashamed that I didn't have the habit of writing test cases diligently. Now, I've written some test cases, covering the scenarios you mentioned. Currently, it seems to be functioning properly.

```json
{"a1": "hello", "a2": "world"}
```

got

```text
message AutoGenerated {
    string a1 = 0;
    string a2 = 1;
}
```
