### ISSUE TITLE
invalid field name

### ISSUE THREAD

**Issue by 3052** [xuthus5/json-to-pb#5]
input

{"_": "hello", "a2": "world"}

output

syntax = "proto3";

package your.project.v1;

option go_package = "your/project;projectv1";

message AutoGenerated {
    string _  = 1;
    string a2 = 2;
}

must start with letter:

https://protobuf.dev/reference/protobuf/proto3-spec/#identifiers

**Comment by xuthus5** [comment]
`_` is a valid token.

input:
```proto
message AutoGenerated {
  double _ = 1;
}
```

run command:
```bash
protoc --go_out=. test.proto
```

got go define:
```go
type AutoGenerated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=_,proto3" json:"_,omitempty"`
}
```

input:
```proto
message _ {
  _ __ = 1;
}
```
got go define:
```go
type X struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X_ *X `protobuf:"bytes,1,opt,name=__,proto3" json:"__,omitempty"`
}
```

**Comment by 3052** [comment]
`protoc` tool does not define the standard. the standard is here:

~~~
ident = letter { letter | decimalDigit | "_" }
~~~

https://protobuf.dev/reference/protobuf/proto3-spec/#identifiers

MUST start with a letter

**Comment by xuthus5** [comment]
@3052 I agree with your, and I will modify the code.
